<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.mobian.model.TfdMemberAppointment" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<script type="text/javascript">
	$(function() {
		parent.$.messager.progress('close');		
	});
</script>
<div class="easyui-layout" data-options="fit:true,border:false">
	<div data-options="region:'center',border:false">
		<table class="table table-hover table-condensed">
				<tr>	
					<th><%=TfdMemberAppointment.ALIAS_TIME%></th>	
					<td>
						${fdMemberAppointment.time}							
					</td>							
					<th><%=TfdMemberAppointment.ALIAS_USER_ID%></th>	
					<td>
						${fdMemberAppointment.userId}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberAppointment.ALIAS_DOCTOR_ID%></th>	
					<td>
						${fdMemberAppointment.doctorId}							
					</td>							
					<th><%=TfdMemberAppointment.ALIAS_APPOINT_TIME%></th>	
					<td>
						${fdMemberAppointment.appointTime}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberAppointment.ALIAS_SECOND_TIME%></th>	
					<td>
						${fdMemberAppointment.secondTime}							
					</td>							
					<th><%=TfdMemberAppointment.ALIAS_APPOINT_NAME%></th>	
					<td>
						${fdMemberAppointment.appointName}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberAppointment.ALIAS_LINK_NAME%></th>	
					<td>
						${fdMemberAppointment.linkName}							
					</td>							
					<th><%=TfdMemberAppointment.ALIAS_LINK_WAY%></th>	
					<td>
						${fdMemberAppointment.linkWay}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberAppointment.ALIAS_APPOINT_MESSAGE%></th>	
					<td>
						${fdMemberAppointment.appointMessage}							
					</td>							
					<th><%=TfdMemberAppointment.ALIAS_CREATE_BY%></th>	
					<td>
						${fdMemberAppointment.createBy}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberAppointment.ALIAS_CREATE_TIME%></th>	
					<td>
						${fdMemberAppointment.createTime}							
					</td>							
					<th><%=TfdMemberAppointment.ALIAS_UPDATE_BY%></th>	
					<td>
						${fdMemberAppointment.updateBy}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberAppointment.ALIAS_UPDATE_TIME%></th>	
					<td>
						${fdMemberAppointment.updateTime}							
					</td>							
					<th><%=TfdMemberAppointment.ALIAS_STATUS%></th>	
					<td>
						${fdMemberAppointment.status}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberAppointment.ALIAS_COUPON_ID%></th>	
					<td>
						${fdMemberAppointment.couponId}							
					</td>							
					<th><%=TfdMemberAppointment.ALIAS_PICS%></th>	
					<td>
						${fdMemberAppointment.pics}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberAppointment.ALIAS_APPOINT_STATUS%></th>	
					<td>
						${fdMemberAppointment.appointStatus}							
					</td>							
					<th><%=TfdMemberAppointment.ALIAS_ADJUSTMENT%></th>	
					<td>
						${fdMemberAppointment.adjustment}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberAppointment.ALIAS_REFUSE_REASON%></th>	
					<td>
						${fdMemberAppointment.refuseReason}							
					</td>							
					<th><%=TfdMemberAppointment.ALIAS_CONFIRM_TIME%></th>	
					<td>
						${fdMemberAppointment.confirmTime}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberAppointment.ALIAS_FIRST_CONFIRM%></th>	
					<td>
						${fdMemberAppointment.firstConfirm}							
					</td>							
					<th><%=TfdMemberAppointment.ALIAS_FILE%></th>	
					<td>
						${fdMemberAppointment.file}							
					</td>							
				</tr>		
		</table>
	</div>
</div>