<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.mobian.model.TfdMember" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<script type="text/javascript">
	$(function() {
		parent.$.messager.progress('close');		
	});
</script>
<div class="easyui-layout" data-options="fit:true,border:false">
	<div data-options="region:'center',border:false">
		<table class="table table-hover table-condensed">
				<tr>	
					<th><%=TfdMember.ALIAS_USERNAME%></th>	
					<td>
						${fdMember.username}							
					</td>							
					<th><%=TfdMember.ALIAS_PASSWORD%></th>	
					<td>
						${fdMember.password}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMember.ALIAS_SCORE%></th>	
					<td>
						${fdMember.score}							
					</td>							
					<th><%=TfdMember.ALIAS_EMAIL%></th>	
					<td>
						${fdMember.email}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMember.ALIAS_LOGIN%></th>	
					<td>
						${fdMember.login}							
					</td>							
					<th><%=TfdMember.ALIAS_MOBILE%></th>	
					<td>
						${fdMember.mobile}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMember.ALIAS_REG_TIME%></th>	
					<td>
						${fdMember.regTime}							
					</td>							
					<th><%=TfdMember.ALIAS_REG_IP%></th>	
					<td>
						${fdMember.regIp}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMember.ALIAS_LAST_LOGIN_TIME%></th>	
					<td>
						${fdMember.lastLoginTime}							
					</td>							
					<th><%=TfdMember.ALIAS_LAST_LOGIN_IP%></th>	
					<td>
						${fdMember.lastLoginIp}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMember.ALIAS_UPDATE_TIME%></th>	
					<td>
						${fdMember.updateTime}							
					</td>							
					<th><%=TfdMember.ALIAS_STATUS%></th>	
					<td>
						${fdMember.status}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMember.ALIAS_IS_ADMIN%></th>	
					<td>
						${fdMember.isAdmin}							
					</td>							
					<th><%=TfdMember.ALIAS_GROUPID%></th>	
					<td>
						${fdMember.groupid}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMember.ALIAS_AMOUNT%></th>	
					<td>
						${fdMember.amount}							
					</td>							
					<th><%=TfdMember.ALIAS_MODELID%></th>	
					<td>
						${fdMember.modelid}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMember.ALIAS_MESSAGE%></th>	
					<td>
						${fdMember.message}							
					</td>							
					<th><%=TfdMember.ALIAS_PIC%></th>	
					<td>
						${fdMember.pic}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMember.ALIAS_DOCTOR_ID%></th>	
					<td>
						${fdMember.doctorId}							
					</td>							
					<th><%=TfdMember.ALIAS_GROUP_ID%></th>	
					<td>
						${fdMember.groupId}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMember.ALIAS_VIP_END_TIME%></th>	
					<td>
						${fdMember.vipEndTime}							
					</td>							
				</tr>		
		</table>
	</div>
</div>