<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.mobian.model.TfdMemberDoctorSh" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<script type="text/javascript">
	$(function() {
		parent.$.messager.progress('close');		
	});
</script>
<div class="easyui-layout" data-options="fit:true,border:false">
	<div data-options="region:'center',border:false">
		<table class="table table-hover table-condensed">
				<tr>	
					<th><%=TfdMemberDoctorSh.ALIAS_LEVEL%></th>	
					<td>
						${fdMemberDoctorSh.level}							
					</td>							
					<th><%=TfdMemberDoctorSh.ALIAS_HOSPITAL%></th>	
					<td>
						${fdMemberDoctorSh.hospital}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberDoctorSh.ALIAS_DEPARTMENT%></th>	
					<td>
						${fdMemberDoctorSh.department}							
					</td>							
					<th><%=TfdMemberDoctorSh.ALIAS_EDUCATION%></th>	
					<td>
						${fdMemberDoctorSh.education}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberDoctorSh.ALIAS_CONSULTING_HOUR%></th>	
					<td>
						${fdMemberDoctorSh.consultingHour}							
					</td>							
					<th><%=TfdMemberDoctorSh.ALIAS_SPECIAL_HOUR%></th>	
					<td>
						${fdMemberDoctorSh.specialHour}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberDoctorSh.ALIAS_SPECIALITY%></th>	
					<td>
						${fdMemberDoctorSh.speciality}							
					</td>							
					<th><%=TfdMemberDoctorSh.ALIAS_INTRODUCE%></th>	
					<td>
						${fdMemberDoctorSh.introduce}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberDoctorSh.ALIAS_PICS%></th>	
					<td>
						${fdMemberDoctorSh.pics}							
					</td>							
					<th><%=TfdMemberDoctorSh.ALIAS_CREATE_BY%></th>	
					<td>
						${fdMemberDoctorSh.createBy}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberDoctorSh.ALIAS_CREATE_TIME%></th>	
					<td>
						${fdMemberDoctorSh.createTime}							
					</td>							
					<th><%=TfdMemberDoctorSh.ALIAS_UPDATE_BY%></th>	
					<td>
						${fdMemberDoctorSh.updateBy}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberDoctorSh.ALIAS_UPDATE_TIME%></th>	
					<td>
						${fdMemberDoctorSh.updateTime}							
					</td>							
					<th><%=TfdMemberDoctorSh.ALIAS_STATUS%></th>	
					<td>
						${fdMemberDoctorSh.status}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberDoctorSh.ALIAS_REASON%></th>	
					<td>
						${fdMemberDoctorSh.reason}							
					</td>							
					<th><%=TfdMemberDoctorSh.ALIAS_REAL_NAME%></th>	
					<td>
						${fdMemberDoctorSh.realName}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberDoctorSh.ALIAS_SEX%></th>	
					<td>
						${fdMemberDoctorSh.sex}							
					</td>							
					<th><%=TfdMemberDoctorSh.ALIAS_BIRTHDAY%></th>	
					<td>
						${fdMemberDoctorSh.birthday}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfdMemberDoctorSh.ALIAS_GROUP_ID%></th>	
					<td>
						${fdMemberDoctorSh.groupId}							
					</td>							
				</tr>		
		</table>
	</div>
</div>